-- MySQL Script generated by MySQL Workbench
-- 03/25/16 17:14:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_forum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_forum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_forum` DEFAULT CHARACTER SET utf8 ;
USE `db_forum` ;

-- -----------------------------------------------------
-- Table `db_forum`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_forum`.`comments` (
  `comment_ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `comment_post_ID` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
  `comment_author` TINYTEXT CHARACTER SET 'utf8mb4' NOT NULL,
  `comment_author_email` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL DEFAULT '',
  `comment_author_url` VARCHAR(200) CHARACTER SET 'utf8mb4' NOT NULL DEFAULT '',
  `comment_author_IP` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL DEFAULT '',
  `comment_date` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_date_gmt` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_content` TEXT CHARACTER SET 'utf8mb4' NOT NULL,
  `comment_karma` INT(11) NOT NULL DEFAULT '0',
  `comment_approved` VARCHAR(20) CHARACTER SET 'utf8mb4' NOT NULL DEFAULT '1',
  `comment_agent` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL DEFAULT '',
  `comment_type` VARCHAR(20) CHARACTER SET 'utf8mb4' NOT NULL DEFAULT '',
  `comment_parent` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
  `user_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`comment_ID`),
  INDEX `comment_post_ID` (`comment_post_ID` ASC),
  INDEX `comment_approved_date_gmt` (`comment_approved` ASC, `comment_date_gmt` ASC),
  INDEX `comment_date_gmt` (`comment_date_gmt` ASC),
  INDEX `comment_parent` (`comment_parent` ASC),
  INDEX `comment_author_email` (`comment_author_email`(10) ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `db_forum`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_forum`.`posts` (
  `ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `post_author` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
  `post_date` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_date_gmt` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content` LONGTEXT CHARACTER SET 'utf8mb4' NOT NULL,
  `post_title` TEXT CHARACTER SET 'utf8mb4' NOT NULL,
  `post_excerpt` TEXT CHARACTER SET 'utf8mb4' NOT NULL,
  `post_status` VARCHAR(20) CHARACTER SET 'utf8mb4' NOT NULL DEFAULT 'publish',
  `comment_status` VARCHAR(20) CHARACTER SET 'utf8mb4' NOT NULL DEFAULT 'open',
  `ping_status` VARCHAR(20) CHARACTER SET 'utf8mb4' NOT NULL DEFAULT 'open',
  `post_password` VARCHAR(20) CHARACTER SET 'utf8mb4' NOT NULL DEFAULT '',
  `post_name` VARCHAR(200) CHARACTER SET 'utf8mb4' NOT NULL DEFAULT '',
  `to_ping` TEXT CHARACTER SET 'utf8mb4' NOT NULL,
  `pinged` TEXT CHARACTER SET 'utf8mb4' NOT NULL,
  `post_modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_modified_gmt` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content_filtered` LONGTEXT CHARACTER SET 'utf8mb4' NOT NULL,
  `post_parent` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
  `guid` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL DEFAULT '',
  `menu_order` INT(11) NOT NULL DEFAULT '0',
  `post_type` VARCHAR(20) CHARACTER SET 'utf8mb4' NOT NULL DEFAULT 'post',
  `post_mime_type` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL DEFAULT '',
  `comment_count` BIGINT(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  INDEX `post_name` (`post_name`(191) ASC),
  INDEX `type_status_date` (`post_type` ASC, `post_status` ASC, `post_date` ASC, `ID` ASC),
  INDEX `post_parent` (`post_parent` ASC),
  INDEX `post_author` (`post_author` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 133
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
